-- MySQL Script generated by MySQL Workbench
-- Sat Mar  7 08:00:33 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema seguridad_nacional
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema seguridad_nacional
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `seguridad_nacional` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`status_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`status_usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`status_usuario` (
  `id_status_usuario` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id_status_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`permisos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`permisos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`permisos` (
  `id_permisos` INT NOT NULL AUTO_INCREMENT,
  `nombre_permiso` VARCHAR(50) NULL,
  PRIMARY KEY (`id_permisos`),
  UNIQUE INDEX `id_permisos_UNIQUE` (`id_permisos` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rol_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`rol_usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`rol_usuario` (
  `id_rol_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_rol_usuario` VARCHAR(45) NULL,
  `permisos_id_permisos` INT NOT NULL,
  PRIMARY KEY (`id_rol_usuario`),
  INDEX `fk_rol_usuario_permisos_idx` (`permisos_id_permisos` ASC) VISIBLE,
  CONSTRAINT `fk_rol_usuario_permisos`
    FOREIGN KEY (`permisos_id_permisos`)
    REFERENCES `mydb`.`permisos` (`id_permisos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(50) NOT NULL,
  `contrasena` VARCHAR(20) NOT NULL,
  `status_usuario_id_status_usuario` INT NOT NULL,
  `rol_usuario_id_rol_usuario` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC) VISIBLE,
  UNIQUE INDEX `nombre_usuario_UNIQUE` (`nombre_usuario` ASC) VISIBLE,
  INDEX `fk_usuario_status_usuario1_idx` (`status_usuario_id_status_usuario` ASC) VISIBLE,
  INDEX `fk_usuario_rol_usuario1_idx` (`rol_usuario_id_rol_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_status_usuario1`
    FOREIGN KEY (`status_usuario_id_status_usuario`)
    REFERENCES `mydb`.`status_usuario` (`id_status_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_rol_usuario1`
    FOREIGN KEY (`rol_usuario_id_rol_usuario`)
    REFERENCES `mydb`.`rol_usuario` (`id_rol_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seguridad_nacional`.`persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seguridad_nacional`.`persona` ;

CREATE TABLE IF NOT EXISTS `seguridad_nacional`.`persona` (
  `id_persona` INT NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NULL DEFAULT NULL,
  `correo` VARCHAR(100) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id_persona`),
  UNIQUE INDEX `dni` (`dni` ASC) VISIBLE,
  UNIQUE INDEX `correo` (`correo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`personal_administrativo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`personal_administrativo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`personal_administrativo` (
  `id_personal_administrativo` INT NOT NULL AUTO_INCREMENT,
  `cargo` VARCHAR(45) NOT NULL,
  `persona_id_persona` INT NOT NULL,
  PRIMARY KEY (`id_personal_administrativo`),
  UNIQUE INDEX `id_personal_administrativo_UNIQUE` (`id_personal_administrativo` ASC) VISIBLE,
  UNIQUE INDEX `cargo_UNIQUE` (`cargo` ASC) VISIBLE,
  INDEX `fk_personal_administrativo_persona1_idx` (`persona_id_persona` ASC) VISIBLE,
  CONSTRAINT `fk_personal_administrativo_persona1`
    FOREIGN KEY (`persona_id_persona`)
    REFERENCES `seguridad_nacional`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_reporte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tipo_reporte` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tipo_reporte` (
  `id_tipo_reporte` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_reporte`),
  UNIQUE INDEX `tipo_UNIQUE` (`tipo` ASC) VISIBLE,
  UNIQUE INDEX `id_tipo_reporte_UNIQUE` (`id_tipo_reporte` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seguridad_nacional`.`status_reporte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seguridad_nacional`.`status_reporte` ;

CREATE TABLE IF NOT EXISTS `seguridad_nacional`.`status_reporte` (
  `id_status_reporte` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_status_reporte`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`reporte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`reporte` ;

CREATE TABLE IF NOT EXISTS `mydb`.`reporte` (
  `id_reporte` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  `tipo_reporte_id_tipo_reporte` INT NOT NULL,
  `status_reporte_id_status_reporte` INT NOT NULL,
  PRIMARY KEY (`id_reporte`),
  UNIQUE INDEX `id_reporte_UNIQUE` (`id_reporte` ASC) VISIBLE,
  INDEX `fk_reporte_usuario1_idx` (`usuario_id_usuario` ASC) VISIBLE,
  INDEX `fk_reporte_tipo_reporte1_idx` (`tipo_reporte_id_tipo_reporte` ASC) VISIBLE,
  INDEX `fk_reporte_status_reporte1_idx` (`status_reporte_id_status_reporte` ASC) VISIBLE,
  CONSTRAINT `fk_reporte_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reporte_tipo_reporte1`
    FOREIGN KEY (`tipo_reporte_id_tipo_reporte`)
    REFERENCES `mydb`.`tipo_reporte` (`id_tipo_reporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reporte_status_reporte1`
    FOREIGN KEY (`status_reporte_id_status_reporte`)
    REFERENCES `seguridad_nacional`.`status_reporte` (`id_status_reporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `seguridad_nacional` ;

-- -----------------------------------------------------
-- Table `seguridad_nacional`.`persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seguridad_nacional`.`persona` ;

CREATE TABLE IF NOT EXISTS `seguridad_nacional`.`persona` (
  `id_persona` INT NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NULL DEFAULT NULL,
  `correo` VARCHAR(100) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id_persona`),
  UNIQUE INDEX `dni` (`dni` ASC) VISIBLE,
  UNIQUE INDEX `correo` (`correo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `seguridad_nacional`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seguridad_nacional`.`usuario` ;

CREATE TABLE IF NOT EXISTS `seguridad_nacional`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(50) NOT NULL,
  `contrasena` VARCHAR(255) NOT NULL,
  `status` TINYINT NULL DEFAULT '1',
  `persona_id_persona` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `nombre_usuario` (`nombre_usuario` ASC) VISIBLE,
  UNIQUE INDEX `persona_id_persona` (`persona_id_persona` ASC) VISIBLE,
  CONSTRAINT `usuario_ibfk_1`
    FOREIGN KEY (`persona_id_persona`)
    REFERENCES `seguridad_nacional`.`persona` (`id_persona`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `seguridad_nacional`.`tipo_reporte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seguridad_nacional`.`tipo_reporte` ;

CREATE TABLE IF NOT EXISTS `seguridad_nacional`.`tipo_reporte` (
  `id_tipo_reporte` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_tipo_reporte`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `seguridad_nacional`.`status_reporte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seguridad_nacional`.`status_reporte` ;

CREATE TABLE IF NOT EXISTS `seguridad_nacional`.`status_reporte` (
  `id_status_reporte` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_status_reporte`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `seguridad_nacional`.`reporte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seguridad_nacional`.`reporte` ;

CREATE TABLE IF NOT EXISTS `seguridad_nacional`.`reporte` (
  `id_reporte` INT NOT NULL AUTO_INCREMENT,
  `fecha_creacion` DATETIME NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `usuario_id_usuario_generador` INT NOT NULL,
  `tipo_reporte_id_tipo_reporte` INT NOT NULL,
  `status_reporte_id_status_reporte` INT NOT NULL,
  PRIMARY KEY (`id_reporte`),
  INDEX `usuario_id_usuario_generador` (`usuario_id_usuario_generador` ASC) VISIBLE,
  INDEX `tipo_reporte_id_tipo_reporte` (`tipo_reporte_id_tipo_reporte` ASC) VISIBLE,
  INDEX `status_reporte_id_status_reporte` (`status_reporte_id_status_reporte` ASC) VISIBLE,
  CONSTRAINT `reporte_ibfk_1`
    FOREIGN KEY (`usuario_id_usuario_generador`)
    REFERENCES `seguridad_nacional`.`usuario` (`id_usuario`),
  CONSTRAINT `reporte_ibfk_2`
    FOREIGN KEY (`tipo_reporte_id_tipo_reporte`)
    REFERENCES `seguridad_nacional`.`tipo_reporte` (`id_tipo_reporte`),
  CONSTRAINT `reporte_ibfk_3`
    FOREIGN KEY (`status_reporte_id_status_reporte`)
    REFERENCES `seguridad_nacional`.`status_reporte` (`id_status_reporte`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `seguridad_nacional`.`alerta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seguridad_nacional`.`alerta` ;

CREATE TABLE IF NOT EXISTS `seguridad_nacional`.`alerta` (
  `id_alerta` INT NOT NULL AUTO_INCREMENT,
  `fecha_hora` DATETIME NOT NULL,
  `mensaje` TEXT NOT NULL,
  `leida` TINYINT(1) NULL DEFAULT '0',
  `usuario_id_usuario_destinatario` INT NOT NULL,
  `reporte_id_reporte` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_alerta`),
  INDEX `usuario_id_usuario_destinatario` (`usuario_id_usuario_destinatario` ASC) VISIBLE,
  INDEX `reporte_id_reporte` (`reporte_id_reporte` ASC) VISIBLE,
  CONSTRAINT `alerta_ibfk_1`
    FOREIGN KEY (`usuario_id_usuario_destinatario`)
    REFERENCES `seguridad_nacional`.`usuario` (`id_usuario`),
  CONSTRAINT `alerta_ibfk_2`
    FOREIGN KEY (`reporte_id_reporte`)
    REFERENCES `seguridad_nacional`.`reporte` (`id_reporte`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `seguridad_nacional`.`conductor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seguridad_nacional`.`conductor` ;

CREATE TABLE IF NOT EXISTS `seguridad_nacional`.`conductor` (
  `id_fk_persona` INT NOT NULL,
  `licencia` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_fk_persona`),
  UNIQUE INDEX `licencia` (`licencia` ASC) VISIBLE,
  CONSTRAINT `conductor_ibfk_1`
    FOREIGN KEY (`id_fk_persona`)
    REFERENCES `seguridad_nacional`.`persona` (`id_persona`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `seguridad_nacional`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seguridad_nacional`.`rol` ;

CREATE TABLE IF NOT EXISTS `seguridad_nacional`.`rol` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_rol`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `seguridad_nacional`.`usuario_rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seguridad_nacional`.`usuario_rol` ;

CREATE TABLE IF NOT EXISTS `seguridad_nacional`.`usuario_rol` (
  `id_usuario_rol` INT NOT NULL AUTO_INCREMENT,
  `usuario_id_usuario` INT NOT NULL,
  `rol_id_rol` INT NOT NULL,
  PRIMARY KEY (`id_usuario_rol`),
  UNIQUE INDEX `uk_usuario_rol` (`usuario_id_usuario` ASC, `rol_id_rol` ASC) VISIBLE,
  INDEX `rol_id_rol` (`rol_id_rol` ASC) VISIBLE,
  CONSTRAINT `usuario_rol_ibfk_1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `seguridad_nacional`.`usuario` (`id_usuario`),
  CONSTRAINT `usuario_rol_ibfk_2`
    FOREIGN KEY (`rol_id_rol`)
    REFERENCES `seguridad_nacional`.`rol` (`id_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `seguridad_nacional`.`supervisor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seguridad_nacional`.`supervisor` ;

CREATE TABLE IF NOT EXISTS `seguridad_nacional`.`supervisor` (
  `usuario_rol_id_usuario_rol` INT NOT NULL,
  `fecha_ascenso` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`usuario_rol_id_usuario_rol`),
  CONSTRAINT `supervisor_ibfk_1`
    FOREIGN KEY (`usuario_rol_id_usuario_rol`)
    REFERENCES `seguridad_nacional`.`usuario_rol` (`id_usuario_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `seguridad_nacional`.`guarda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seguridad_nacional`.`guarda` ;

CREATE TABLE IF NOT EXISTS `seguridad_nacional`.`guarda` (
  `usuario_rol_id_usuario_rol` INT NOT NULL,
  `areaAsignada` VARCHAR(50) NOT NULL,
  `supervisor_id_supervisor` INT NULL DEFAULT NULL,
  PRIMARY KEY (`usuario_rol_id_usuario_rol`),
  INDEX `supervisor_id_supervisor` (`supervisor_id_supervisor` ASC) VISIBLE,
  CONSTRAINT `guarda_ibfk_1`
    FOREIGN KEY (`usuario_rol_id_usuario_rol`)
    REFERENCES `seguridad_nacional`.`usuario_rol` (`id_usuario_rol`),
  CONSTRAINT `guarda_ibfk_2`
    FOREIGN KEY (`supervisor_id_supervisor`)
    REFERENCES `seguridad_nacional`.`supervisor` (`usuario_rol_id_usuario_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `seguridad_nacional`.`personal_administrativo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seguridad_nacional`.`personal_administrativo` ;

CREATE TABLE IF NOT EXISTS `seguridad_nacional`.`personal_administrativo` (
  `usuario_rol_id_usuario_rol` INT NOT NULL,
  `cargo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`usuario_rol_id_usuario_rol`),
  CONSTRAINT `personal_administrativo_ibfk_1`
    FOREIGN KEY (`usuario_rol_id_usuario_rol`)
    REFERENCES `seguridad_nacional`.`usuario_rol` (`id_usuario_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `seguridad_nacional`.`vehiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seguridad_nacional`.`vehiculo` ;

CREATE TABLE IF NOT EXISTS `seguridad_nacional`.`vehiculo` (
  `id_vehiculo` INT NOT NULL AUTO_INCREMENT,
  `placa` VARCHAR(10) NOT NULL,
  `conductor_id_fk_persona` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_vehiculo`),
  UNIQUE INDEX `placa` (`placa` ASC) VISIBLE,
  INDEX `conductor_id_fk_persona` (`conductor_id_fk_persona` ASC) VISIBLE,
  CONSTRAINT `vehiculo_ibfk_1`
    FOREIGN KEY (`conductor_id_fk_persona`)
    REFERENCES `seguridad_nacional`.`conductor` (`id_fk_persona`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
